name: 在Intel Mac上编译Airplay2版本

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: 安装依赖
        run: |
          brew install automake
          brew install popt
          brew install libconfig
          brew install libao
          brew install libsoxr
          brew install openssl
      - name: 编译和安装NQPTP
        run: |
          git clone https://github.com/mikebrady/nqptp.git
          cd nqptp
          autoreconf -fi
          ./configure
          make
          sudo make install
          cd ..
      - name: 配置Shairport Sync
        run: |
          autoreconf -fi
          ./configure --with-os=darwin --with-airplay-2 --with-ao --with-pipe --with-soxr --with-stdout --with-dns_sd --with-ssl=openssl
      - name: 编译Shairport Sync
        run: |
          make
      - name: 上传编译结果
        uses: actions/upload-artifact@v4
        with:
          name: shairport-sync-airplay2-mac-intel
          path: shairport-sync
